declare module '@editorjs/header';
declare module '@editorjs/list';
declare module '@editorjs/quote';
declare module '@editorjs/image';
declare module '@editorjs/table';
declare module '@editorjs/delimiter';
declare module '@editorjs/embed';
declare module '@editorjs/link';
declare module '@editorjs/paragraph';
